freebsd_instance:
  image_family: freebsd-14-0-snap

task:
  name: FreeBSD
  env:
    IGNORE_OSVERSION: yes
  skip_notifications: true
  prerequisites_script:
    - pkg update -f
    - pkg upgrade -y
    - pkg install -y devel/pkgconf graphics/vips www/node16 www/npm
  install_script:
    - npm install --build-from-source --unsafe-perm
  test_script:
    - npm test
