freebsd_instance:
  image_family: freebsd-13-0-snap

task:
  prerequisites_script:
    - pkg update -f
    - pkg upgrade -y
    - pkg install -y pkgconf vips node npm
  install_script:
    - npm install --unsafe-perm
  test_script:
    - npm test
