language: node_js
node_js:
  - "0.11"
  - "0.10"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libvips-dev imagemagick
 - sudo ln -s /usr/lib/pkgconfig/vips-7.26.pc /usr/lib/pkgconfig/vips.pc