jobs:
  include:
    - name: "Linux ARM64v8 (Debian 11, glibc 2.29) - Node.js 10"
      arch: arm64
      os: linux
      dist: bionic
      language: shell
      before_install:
        - sudo docker run -dit --name sharp --volume "${PWD}:/mnt/sharp" --workdir /mnt/sharp arm64v8/debian:bullseye
        - sudo docker exec sharp sh -c "apt-get update && apt-get install -y build-essential git python3 curl"
        - sudo docker exec sharp sh -c "curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -"
        - sudo docker exec sharp sh -c "echo 'deb https://deb.nodesource.com/node_10.x sid main' >/etc/apt/sources.list.d/nodesource.list"
        - sudo docker exec sharp sh -c "apt-get update && apt-get install -y nodejs=10.*"
      install: sudo docker exec sharp sh -c "npm install --build-from-source --unsafe-perm"
      script: sudo docker exec sharp sh -c "npm test"
      after_success: "[[ -n $TRAVIS_TAG ]] && sudo docker exec --env prebuild_upload sharp sh -c \"npx prebuild --runtime napi --target 3\""

    - name: "Linux ARM64v8 (Debian 11, glibc 2.29) - Node.js 12"
      arch: arm64
      os: linux
      dist: bionic
      language: shell
      before_install:
        - sudo docker run -dit --name sharp --volume "${PWD}:/mnt/sharp" --workdir /mnt/sharp arm64v8/debian:bullseye
        - sudo docker exec sharp sh -c "apt-get update && apt-get install -y build-essential git python3 curl"
        - sudo docker exec sharp sh -c "curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -"
        - sudo docker exec sharp sh -c "echo 'deb https://deb.nodesource.com/node_12.x sid main' >/etc/apt/sources.list.d/nodesource.list"
        - sudo docker exec sharp sh -c "apt-get update && apt-get install -y nodejs"
      install: sudo docker exec sharp sh -c "npm install --build-from-source --unsafe-perm"
      script: sudo docker exec sharp sh -c "npm test"

    - name: "Linux ARM64v8 (Debian 11, glibc 2.29) - Node.js 14"
      arch: arm64
      os: linux
      dist: bionic
      language: shell
      before_install:
        - sudo docker run -dit --name sharp --volume "${PWD}:/mnt/sharp" --workdir /mnt/sharp arm64v8/debian:bullseye
        - sudo docker exec sharp sh -c "apt-get update && apt-get install -y build-essential git python3 curl"
        - sudo docker exec sharp sh -c "curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -"
        - sudo docker exec sharp sh -c "echo 'deb https://deb.nodesource.com/node_14.x sid main' >/etc/apt/sources.list.d/nodesource.list"
        - sudo docker exec sharp sh -c "apt-get update && apt-get install -y nodejs"
      install: sudo docker exec sharp sh -c "npm install --build-from-source --unsafe-perm"
      script: sudo docker exec sharp sh -c "npm test"

    - name: "Linux ARM64v8 (Debian 11, glibc 2.29) - Node.js 15"
      arch: arm64
      os: linux
      dist: bionic
      language: shell
      before_install:
        - sudo chown 0.0 ${PWD}
        - sudo docker run -dit --name sharp --volume "${PWD}:/mnt/sharp" --workdir /mnt/sharp arm64v8/debian:bullseye
        - sudo docker exec sharp sh -c "apt-get update && apt-get install -y build-essential git python3 curl"
        - sudo docker exec sharp sh -c "curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -"
        - sudo docker exec sharp sh -c "echo 'deb https://deb.nodesource.com/node_15.x sid main' >/etc/apt/sources.list.d/nodesource.list"
        - sudo docker exec sharp sh -c "apt-get update && apt-get install -y nodejs"
      install: sudo docker exec sharp sh -c "npm install --build-from-source --unsafe-perm"
      script: sudo docker exec sharp sh -c "npm test"

cache:
  npm: false
