site_name: sharp
site_url: http://sharp.dimens.io/
repo_url: https://github.com/lovell/sharp
site_description: High performance Node.js image processing, the fastest module to resize JPEG, PNG, WebP and TIFF images
copyright: <a href="https://dimens.io/">dimens.io</a>
google_analytics: ['UA-13034748-12', 'sharp.dimens.io']
theme: readthedocs
markdown_extensions:
  - toc:
      permalink: True
dev_addr: 0.0.0.0:10101
pages:
  - Home: index.md
  - Installation: install.md
  - API:
    - Constructor: api-constructor.md
    - Input: api-input.md
    - Output: api-output.md
    - "Resizing images": api-resize.md
    - "Compositing images": api-composite.md
    - "Image operations": api-operation.md
    - "Colour manipulation": api-colour.md
    - "Channel manipulation": api-channel.md
    - Utilities: api-utility.md
  - Performance: performance.md
  - Changelog: changelog.md
